syntax on
set encoding=utf8
set autoindent
set copyindent
set expandtab
set tabstop=4
set shiftwidth=4
set smarttab
set ignorecase
set smartcase
set hlsearch
set incsearch
set visualbell
set title
set showmatch
set hidden
filetype plugin indent on
set pastetoggle=<F2>
noremap ; :
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

if &term =~# '^\(tmux\|st\)'
    set termguicolors
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

