#!/bin/sh

BSPWM_CFG=~/.config/bspwm

. $BSPWM_CFG/theme

xsetroot -cursor_name left_ptr
hsetroot -solid "#1a1b26"

pkill -x redshift;  redshift &
pkill -x sxhkd;     sxhkd -r /dev/null &
pkill -x dunst;     dunst &
pkill -x picom; picom -b &

bspc monitor DisplayPort-1 -d 1 2
bspc monitor DisplayPort-0 -d 3 4 5 6 7 8
bspc monitor DisplayPort-2 -d 9 0

bspc config border_width           2
bspc config window_gap             7

bspc config split_ratio            0.5
bspc config gapless_monocle        false
bspc config ignore_ewmh_fullscreen all

bspc config presel_feedback_color  "$COLOR_NORM"
bspc config normal_border_color    "$COLOR_4"
bspc config focused_border_color   "$COLOR_NORM"
bspc config active_border_color    "$COLOR_4"

bspc config pointer_modifier       mod4
bspc config pointer_action1        move
bspc config pointer_action2        resize_corner
bspc config pointer_action3        resize_side

bspc config status_prefix         'bspwm)'

bspc rule -a Zathura 'state=tiled'
bspc config external_rules_command $BSPWM_CFG/rules_cmd

pkill -x panel; $BSPWM_CFG/panel/panel &

bspc config top_padding 20

alacritty -e nvim ~/Documents/notes/index.md &
