#! /bin/sh

. ~/.config/bspwm/theme

~/.fehbg &
BGSET=$!
xsetroot -cursor_name left_ptr
xset -led 1
xset dpms 0 0 600

pkill -x redshift;  redshift &
pkill -x sxhkd;     sxhkd -r /dev/null &
#pkill -x xautolock; xautolock -detectsleep -time 12 -locker "sudo pm-suspend" &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         3
bspc config window_gap           15
bspc config top_padding          -5

bspc config split_ratio          0.5
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config ignore_ewmh_fullscreen all

bspc config presel_feedback_color "$COLOR_NORM"
bspc config normal_border_color   "$COLOR_4"
bspc config focused_border_color  "$COLOR_NORM"
bspc config active_border_color   "$COLOR_HIGH"

bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_corner
bspc config pointer_action3       resize_side
#bspc config focus_follows_pointer true

bspc config status_prefix         'bspwm)'

bspc rule -a Zathura 'state=tiled'

wait $BGSET
pkill -x compton; compton -CGb &
pkill -x panel; nohup "${XDG_CONFIG_HOME}/bspwm/panel/panel" > /dev/null 2>&1 &
#pkill -x dunst; dunst &

alacritty -e nvim ~/Documents/notes/index.md &

