#!/bin/sh

#export GDK_DPI_SCALE=1.5

#enable keyboard light control
xkbcomp $DISPLAY /tmp/kbconf.xkb
sed -i 's/!allowExplicit/allowExplicit/g' /tmp/kbconf.xkb
xkbcomp /tmp/kbconf.xkb $DISPLAY > /dev/null 2>&1
rm /tmp/kbconf.xkb

xmodmap ~/.Xmodmap
xrdb ~/.Xresources
#xset -r 66
xset -led 1
xset b off

xcape -e '0x3000=Escape'
syndaemon -t -K -i 1.5 -d -R

