export PATH="$HOME/.local/bin:$PATH"
export EDITOR=nvim

export RUST_SRC_PATH="/usr/lib64/rust-1.29.2/rustlib/src/rust/src"
export PYTHONSTARTUP="$HOME/.config/python/pythonrc"
export MPD_HOST="$HOME/.local/share/mpd/socket"
export XDG_CONFIG_HOME="$HOME/.config"

export FZF_DEFAULT_COMMAND='fd --type file --color=always --follow --hidden --exclude .git'
export FZF_DEFAULT_OPTS="--ansi"

source "$HOME/.colors"
