HISTFILE="$HOME/.local/share/zsh/history"

if [[ ! -v LS_COLORS ]]; then
    dircolors -b /etc/DIR_COLORS | source /dev/stdin
fi

HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd nomatch promptsubst histignorespace nobeep nonotify
bindkey -e

# The following lines were added by compinstall
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*' accept-exact-dirs true
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$HOME/.cache/zsh"
zstyle :compinstall filename "$ZDOTDIR/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

prompt_color=$(printf "%d;%d;%d\n" 0x${COLOR_NORM:1:2} 0x${COLOR_NORM:3:2} 0x${COLOR_NORM:5:2})
PROMPT=$'%(?..%B%F{1}%? %b%f)%{\x1b[38;2;${prompt_color}m%}%1/> %{\x1b[0m%}'

precmd () {print -Pn "\e]2;%~\a"}

alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias diff='diff --color=auto'
alias cp='cp --reflink=auto'

if [[ "$INSIDE_EMACS" = 'vterm' ]] \
    && [[ -n ${EMACS_VTERM_PATH} ]] \
    && [[ -f ${EMACS_VTERM_PATH}/etc/emacs-vterm-zsh.sh ]]; then
    source ${EMACS_VTERM_PATH}/etc/emacs-vterm-zsh.sh
fi
